
name: CD - Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJ_ID }}  
      - name: Deploy to GCE
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.GCP_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.GCP_PRIVATE_KEY }}
            script: |
                cd fastapi-app
                git stash
                git pull origin main
                source venv/bin/activate
                pip install -r requirements.txt
                sudo systemctl restart fastapi
