
name: CD - Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Authenticate with GCP'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'polar-land-450610-r5'
          workload_identity_provider: 'projects/350557131038/locations/global/workloadIdentityPools/github-actions-provider/providers/github-actions-pool'
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJ_ID }}
      - name: 'Describe Secrets'
        run: |
             gcloud secrets describe "my-secret" --project="polar-land-450610-r5"          
        
      - name: Deploy to GCE
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.GCP_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.GCP_PRIVATE_KEY }}
            script: |
                cd fastapi-book-project
                git stash
                git pull origin main
                source venv/bin/activate
                pip install -r requirements.txt
                sudo systemctl restart fastapi
